### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by dborowik** [haschdl/pLaunchPadMini#3]
Processing sometimes throw the error as 'library not found' (Processing v3.3.7). 
It works fine with Example 1 but the two other Examples throw the error.

I have installed the library from the 'Release' version available here.

**Comment by haschdl** [comment]
Hi @dborowik ! Check the new release, it should be fixed now. 
https://github.com/haschdl/pLaunchPadMini/releases/tag/1.1

**Comment by dborowik** [comment]
Thank you for your speedy response. Very sorry but on the most recent OSX I
have both zip released extract as another 'zip.cpgz' compressed file, I am
not sure how to extract further.

I will check on my 10.9.2 machine later where I could extract the library

**Comment by dborowik** [comment]
Sorry I managed with good old StuffItExpander. checking now

**Comment by dborowik** [comment]
Grrr I am still getting

The package “launchPadMiniClient” does not exist. You might be missing a
library.
Libraries must be installed in a folder named 'libraries' inside the
sketchbook folder (see the Preferences window).
